### ISSUE TITLE
regex error during using paramter L#

### ISSUE THREAD

**Issue by daihongok** [multilang-depends/depends#7]
version :0.9.1

command line parameter:
java -jar depends.jar -d D:\Workspace\Architecture\arch-dataset\cassancra_out  -f=xml java D:\Workspace\Architecture\arch-dataset\apache-cassandra-1.0.7-src\src depends_cassandra_1_0_7_l3_xml  -s -g=L3

java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at depends.matrix.transform.MatrixLevelReducer.calcuateNodeAtLevel(MatrixLevelReducer.java:92)
        at depends.matrix.transform.MatrixLevelReducer.shrinkToLevel(MatrixLevelReducer.java:53)
        at depends.Main.executeCommand(Main.java:124)
        at depends.Main.main(Main.java:60)

**Comment by gangz** [comment]
Resolved.
